name: EKS Creation
on: [push]
jobs:
  create-eks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make install_eksctl
      - run: make install_helm
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      - run: make create_eks
      - run: make create_kube_config
  install_argo:
    runs-on: ubuntu-latest
    steps:
      - run: make install_argo
    needs: create-eks

