name: EKS Creation
on: [push]
jobs:
  create-eks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make install_eksctl
      - run: make install_helm
      - run: make create_eks

